[package]
name = "whippit-lsp"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
lsp-server = "0.7.8"
lsp-types = "=0.97.0"
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
